//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 07:16:36 AM IST 
//


package com.calypso.jaxb.swift;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.calypso.tk.bo.swift.ParsedTemplateElement;



/**
 * The base type for a SWIFT Item.
 * 
 * <p>Java class for ItemDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemDef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modes" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="condition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hasField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="withValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hasValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemDef")
public class ItemDefType
    extends ParsedTemplateElement
{

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "modes", required = true)
    protected String modes;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "condition")
    protected String condition;
    @XmlAttribute(name = "filter")
    protected String filter;
    @XmlAttribute(name = "hasField")
    protected String hasField;
    @XmlAttribute(name = "withValue")
    protected String withValue;
    @XmlAttribute(name = "hasValue")
    protected String hasValue;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the modes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModes() {
        return modes;
    }

    /**
     * Sets the value of the modes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModes(String value) {
        this.modes = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

    /**
     * Gets the value of the hasField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasField() {
        return hasField;
    }

    /**
     * Sets the value of the hasField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasField(String value) {
        this.hasField = value;
    }

    /**
     * Gets the value of the withValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithValue() {
        return withValue;
    }

    /**
     * Sets the value of the withValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithValue(String value) {
        this.withValue = value;
    }

    /**
     * Gets the value of the hasValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasValue() {
        return hasValue;
    }

    /**
     * Sets the value of the hasValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasValue(String value) {
        this.hasValue = value;
    }

}
