//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 07:16:36 AM IST 
//


package com.calypso.jaxb.swift;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import  com.calypso.tk.bo.swift.ParsedTemplateElement;


/**
 * <p>Java class for ModeSelectionList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModeSelectionList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ModeSelection" type="{}ModeSelection" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModeSelectionList", propOrder = {
    "modeSelection"
})
public class ModeSelectionListType
    extends ParsedTemplateElement
{

    @XmlElement(name = "ModeSelection", required = true)
    protected List<ModeSelectionType> modeSelection;

    /**
     * Gets the value of the modeSelection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modeSelection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModeSelection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModeSelectionType }
     * 
     * 
     */
    public List<ModeSelectionType> getModeSelection() {
        if (modeSelection == null) {
            modeSelection = new ArrayList<ModeSelectionType>();
        }
        return this.modeSelection;
    }

}
