//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 07:16:36 AM IST 
//


package com.calypso.jaxb.swift;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.calypso.jaxb.swift package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SwiftMsgDef_QNAME = new QName("", "SwiftMsgDef");
    private final static QName _SwiftSequence_QNAME = new QName("", "SwiftSequence");
    private final static QName _SwiftFieldOption_QNAME = new QName("", "SwiftFieldOption");
    private final static QName _SwiftItem_QNAME = new QName("", "SwiftItem");
    private final static QName _SwiftOption_QNAME = new QName("", "SwiftOption");
    private final static QName _SwiftField_QNAME = new QName("", "SwiftField");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.calypso.jaxb.swift
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SwiftMsgDefElement }
     * 
     */
    public SwiftMsgDefElement createSwiftMsgDefElement() {
        return new SwiftMsgDefElement();
    }

    /**
     * Create an instance of {@link ModeSelectionListType }
     * 
     */
    public ModeSelectionListType createModeSelectionListType() {
        return new ModeSelectionListType();
    }

    /**
     * Create an instance of {@link ModeSelectionType }
     * 
     */
    public ModeSelectionType createModeSelectionType() {
        return new ModeSelectionType();
    }

    /**
     * Create an instance of {@link SwiftOptionElement }
     * 
     */
    public SwiftOptionElement createSwiftOptionElement() {
        return new SwiftOptionElement();
    }

    /**
     * Create an instance of {@link ItemDefType }
     * 
     */
    public ItemDefType createItemDefType() {
        return new ItemDefType();
    }

    /**
     * Create an instance of {@link SwiftSequenceElement }
     * 
     */
    public SwiftSequenceElement createSwiftSequenceElement() {
        return new SwiftSequenceElement();
    }

    /**
     * Create an instance of {@link SwiftFieldElement }
     * 
     */
    public SwiftFieldElement createSwiftFieldElement() {
        return new SwiftFieldElement();
    }

    /**
     * Create an instance of {@link SwiftFieldOptionElement }
     * 
     */
    public SwiftFieldOptionElement createSwiftFieldOptionElement() {
        return new SwiftFieldOptionElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwiftMsgDefElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SwiftMsgDef")
    public JAXBElement<SwiftMsgDefElement> createSwiftMsgDef(SwiftMsgDefElement value) {
        return new JAXBElement<SwiftMsgDefElement>(_SwiftMsgDef_QNAME, SwiftMsgDefElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwiftSequenceElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SwiftSequence", substitutionHeadNamespace = "", substitutionHeadName = "SwiftItem")
    public JAXBElement<SwiftSequenceElement> createSwiftSequence(SwiftSequenceElement value) {
        return new JAXBElement<SwiftSequenceElement>(_SwiftSequence_QNAME, SwiftSequenceElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwiftFieldOptionElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SwiftFieldOption", substitutionHeadNamespace = "", substitutionHeadName = "SwiftOption")
    public JAXBElement<SwiftFieldOptionElement> createSwiftFieldOption(SwiftFieldOptionElement value) {
        return new JAXBElement<SwiftFieldOptionElement>(_SwiftFieldOption_QNAME, SwiftFieldOptionElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemDefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SwiftItem")
    public JAXBElement<ItemDefType> createSwiftItem(ItemDefType value) {
        return new JAXBElement<ItemDefType>(_SwiftItem_QNAME, ItemDefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwiftOptionElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SwiftOption")
    public JAXBElement<SwiftOptionElement> createSwiftOption(SwiftOptionElement value) {
        return new JAXBElement<SwiftOptionElement>(_SwiftOption_QNAME, SwiftOptionElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwiftFieldElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SwiftField", substitutionHeadNamespace = "", substitutionHeadName = "SwiftItem")
    public JAXBElement<SwiftFieldElement> createSwiftField(SwiftFieldElement value) {
        return new JAXBElement<SwiftFieldElement>(_SwiftField_QNAME, SwiftFieldElement.class, null, value);
    }

}
