//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 07:16:36 AM IST 
//


package com.calypso.jaxb.swift;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType; 
import com.calypso.tk.bo.swift.ParsedTemplateElement;


/**
 * <p>Java class for SwiftMsgDefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SwiftMsgDefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CancellationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModeSelectionList" type="{}ModeSelectionList"/>
 *         &lt;sequence>
 *           &lt;element ref="{}SwiftSequence" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwiftMsgDefType", propOrder = {
    "name",
    "cancellationName",
    "modeSelectionList",
    "swiftSequence"
})
public class SwiftMsgDefElement
    extends ParsedTemplateElement
{

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "CancellationName")
    protected String cancellationName;
    @XmlElement(name = "ModeSelectionList", required = true)
    protected ModeSelectionListType modeSelectionList;
    @XmlElement(name = "SwiftSequence", required = true)
    protected List<SwiftSequenceElement> swiftSequence;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cancellationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationName() {
        return cancellationName;
    }

    /**
     * Sets the value of the cancellationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationName(String value) {
        this.cancellationName = value;
    }

    /**
     * Gets the value of the modeSelectionList property.
     * 
     * @return
     *     possible object is
     *     {@link ModeSelectionListType }
     *     
     */
    public ModeSelectionListType getModeSelectionList() {
        return modeSelectionList;
    }

    /**
     * Sets the value of the modeSelectionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModeSelectionListType }
     *     
     */
    public void setModeSelectionList(ModeSelectionListType value) {
        this.modeSelectionList = value;
    }

    /**
     * Gets the value of the swiftSequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the swiftSequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSwiftSequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SwiftSequenceElement }
     * 
     * 
     */
    public List<SwiftSequenceElement> getSwiftSequence() {
        if (swiftSequence == null) {
            swiftSequence = new ArrayList<SwiftSequenceElement>();
        }
        return this.swiftSequence;
    }

}
