//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 07:16:36 AM IST 
//


package com.calypso.jaxb.swift;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SequenceDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SequenceDef">
 *   &lt;complexContent>
 *     &lt;extension base="{}ItemDef">
 *       &lt;sequence>
 *         &lt;element ref="{}SwiftItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="openTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="closeTag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iterator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SequenceDef", propOrder = {
    "swiftItem"
})
public class SwiftSequenceElement
    extends ItemDefType
{

    @XmlElementRef(name = "SwiftItem", type = JAXBElement.class)
    protected List<JAXBElement<? extends ItemDefType>> swiftItem;
    @XmlAttribute(name = "openTag")
    protected String openTag;
    @XmlAttribute(name = "closeTag")
    protected String closeTag;
    @XmlAttribute(name = "iterator")
    protected String iterator;

    /**
     * Gets the value of the swiftItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the swiftItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSwiftItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SwiftSequenceElement }{@code >}
     * {@link JAXBElement }{@code <}{@link SwiftFieldElement }{@code >}
     * {@link JAXBElement }{@code <}{@link ItemDefType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends ItemDefType>> getSwiftItem() {
        if (swiftItem == null) {
            swiftItem = new ArrayList<JAXBElement<? extends ItemDefType>>();
        }
        return this.swiftItem;
    }

    /**
     * Gets the value of the openTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenTag() {
        return openTag;
    }

    /**
     * Sets the value of the openTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenTag(String value) {
        this.openTag = value;
    }

    /**
     * Gets the value of the closeTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloseTag() {
        return closeTag;
    }

    /**
     * Sets the value of the closeTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseTag(String value) {
        this.closeTag = value;
    }

    /**
     * Gets the value of the iterator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterator() {
        return iterator;
    }

    /**
     * Sets the value of the iterator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterator(String value) {
        this.iterator = value;
    }

}
