
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 12 07:51:45 IST 2014
//----------------------------------------------------

package bo.html.Formatter.Util;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 16;
  public static final int EMPTY = 24;
  public static final int PERIOD = 27;
  public static final int SEMIC = 26;
  public static final int LPAREN = 10;
  public static final int KEYWORD_DELIM = 29;
  public static final int PRODUCT = 39;
  public static final int TRADE = 36;
  public static final int DATE = 45;
  public static final int RPAREN = 11;
  public static final int NOT = 7;
  public static final int AND = 5;
  public static final int LT = 14;
  public static final int START_REGEN = 3;
  public static final int IN = 22;
  public static final int OR = 6;
  public static final int COMMA = 28;
  public static final int ITERATOR = 31;
  public static final int IF = 30;
  public static final int EOF = 0;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int TRANSFER = 37;
  public static final int LIKE = 21;
  public static final int INCLUDE = 32;
  public static final int LBLOCK = 12;
  public static final int EQEQ = 19;
  public static final int NUMBER = 43;
  public static final int NEQ = 20;
  public static final int START = 2;
  public static final int EQ = 18;
  public static final int GTE = 17;
  public static final int RBLOCK = 13;
  public static final int ELSE = 35;
  public static final int NOTIN = 23;
  public static final int SENDER = 40;
  public static final int MESSAGE = 38;
  public static final int NOTEMPTY = 25;
  public static final int END = 4;
  public static final int STRING = 44;
  public static final int RECEIVER = 41;
  public static final int INLINE = 33;
  public static final int FALSE = 9;
  public static final int GT = 15;
  public static final int SET = 34;
  public static final int IDENTIFIER = 42;
}

