import java.awt.BorderLayout;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import com.jidesoft.plaf.LookAndFeelFactory;

import dsServices.RemoteTrade;
import dsServices.ServerConnectionUtil;

import apps.window.reportwindow.jideReport.PivotReport;
import apps.window.reportwindow.jideReport.SwingReportDemo;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame2.java
 *
 * Created on 7 Apr, 2013, 2:40:21 PM
 */
/**
 *
 * @author MPankaj
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /** Creates new form NewJFrame2 */
	
    public NewJFrame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	String reportsColumns ="producttype,id ,tradedesc1,cpID,traderID,status,type,tradeDate,bookId,quantity,price,nominal";
    	PivotReport pReport = new PivotReport(null);
    	 String sql = " select " + reportsColumns + " from trade";
    	 
   	   ServerConnectionUtil de = null;
		try {
			de =ServerConnectionUtil.connect("localhost", 1099,"127.0.0.1" );
			RemoteTrade remoteTrade;
			//S
			
			remoteTrade = (RemoteTrade)	de.getRMIService("Trade");
			Vector v1 = (Vector) remoteTrade.getTradesforReport(sql);
			pReport.setHeader((Vector) v1.get(0));
			pReport.setdatatype((Vector) v1.get(1));
			pReport.setData((Vector) v1.get(2));
			
			System.out.println("ppp");
		
		}catch(Exception ed) {
			System.out.println(ed);
			
		}
		 
		JPanel jpanel2 = new JPanel();
		//jpanel2 = new javax.swing.JPanel();
		 LookAndFeelFactory.installDefaultLookAndFeelAndExtension();
		ReportDatepanel datePanel = new ReportDatepanel();
  ReportProductPanel productPanel = new ReportProductPanel();
  ReportTradeParamPanel tradePanel = new ReportTradeParamPanel();
        
      
        
        
    
		SwingReportDemo  demo = new SwingReportDemo(pReport);
//		 jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Report"));
        jPanel1 = demo.run();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(demo.getControlPanel(), BorderLayout.NORTH);
        jPanel1.add(demo.getView().getJidePanel(), BorderLayout.CENTER);
       jPanel1.add(tradePanel,BorderLayout.WEST);
       
       
    //   jpanel2.setLayout(new BorderLayout());
   //    jpanel2.add(l1);
     //  jpanel2.add(dd);
       //jpanel2.add(l2);
      // jpanel2.add(dd1);
       
     //  jpanel2.add(l3,BorderLayout.EAST);
     //  jpanel2.add(dd2);
       
   add(jPanel1);
       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       
        
        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
            	NewJFrame2  	m_frame =   new NewJFrame2();
            	m_frame.setVisible(true);
               m_frame.pack();
               m_frame.setSize(1250, 750);
            //   SwingReportDemo demo = new SwingReportDemo(null);
              // frame.add(demo);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration
}
